### ISSUE TITLE
Latest tag for image

### ISSUE THREAD

**Issue by aptonline** [way5/docker-webone#1]
Thanks for making docker version of WebOne, you can see if in use https://mas.to/@apt/109335982063570798

Would it be possible to add a latest tag to your docker builds to make it easier to upgrade if and when future versions appear.

Many thanks.

**Comment by way5** [comment]
Hi @aptonline. I'm glad that you find it useful. I'll be publishing WebOne docker images with "latest" tag, beginning from the next release.
