### ISSUE TITLE
Building for rPI 4

### ISSUE THREAD

**Issue by my05** [way5/docker-webone#2]
Hi,

First of all - a huge thank you for making this into a very useful Docker image. I usually run it on my Qnap using containerstation 3.

This evening, i tried to clone and build it for my rPI 4 (8GB) and it will proceed without issues, but when starting it will soon exit with a 

"/webone.serve: line 1: syntax error: unexpected "("" in the logs. Are there any missing steps (on my behalf)?

**Comment by way5** [comment]
Hi @my05 ,

- Which repo you're building from?  Are you running docker on your Raspberry?
- May I see building script?

> (!) if you're trying to make a barebone webone install (this is actually more favorable in terms of performance), I'd recommend you to consider [webone.arm.sh](https://github.com/way5/webone/blob/sandbox/autoinstall/webone.arm.sh) script.

~

**Comment by my05** [comment]
Hi, i  cloned the repo at https://github.com/way5/docker-webone

Yes, i run docker on the rPI 4 with the following version

pi@raspberrypi:~/project $ docker -v
Docker version 24.0.7, build afdd53b

I build it according to instructions on the page, i.e

 docker build --no-cache -t webone .
 
 and it works without issues. Then i run it using:
 
 docker run -d -p 8090:8090 -v ~/webone.conf:/home/webone  --name  webone-proxy webone
 
 (my webone.conf is in my home directory) and it seems successful at first:
 
 pi@raspberrypi:~/project/docker-webone $ docker run -d -p 8090:8090 -v ~/webone.conf:/home/webone  --name  webone-proxy webone
be244e160f2c9283909683c675effc465b16e100b9993d13567eee44a7357d3d
pi@raspberrypi:~/project/docker-webone $


It then starts, but exits rather quickly and the log simply says '/webone.serve: line 1: syntax error: unexpected "("'


I also tried the webone.arm.sh script and it builds, but the make step fails with a 

'raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/wiki/ Requires=network-online.tar'

**Comment by way5** [comment]
Which OS + version you have installed on your PI?

**Comment by my05** [comment]
Will try it. Thx

My OS and version info:

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by my05** [comment]
Removed those lines and re-ran it, but it stumbled on this:

               ______
___      _________  /___________________
__ | /| / /  _ \_  __ \  __ \_  __ \  _ \
__ |/ |/ //  __/  /_/ / /_/ /  / / /  __/
____/|__/ \___//_.___/\____//_/ /_/\___/
----------------------------------------
                    by Alexander Tauenis



- PREPARE

Already up to date.

- INSTALLATION

- entering /usr/local/webone
- entering /etc/webone
- entering /home/pi/webone

-- Build

MSBuild version 17.7.4+3ebbd7c49 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  WebOne -> /home/pi/webone/bin/Debug/net6.0/linux-arm64/webone.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:05.60

-- Make

MSBuild version 17.7.4+3ebbd7c49 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  WebOne -> /home/pi/webone/bin/Release/net6.0/linux-arm64/webone.dll
/root/.dotnet/sdk/7.0.404/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(296,5): error MSB3030: Could not copy the file "/home/pi/webone/webone.logrotate" because it was not found. [/home/pi/webone/WebOne.csproj]
/root/.dotnet/sdk/7.0.404/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(296,5): error MSB3030: Could not copy the file "/home/pi/webone/webone.service" because it was not found. [/home/pi/webone/WebOne.csproj]

-- Install

rm: cannot remove 'webone.service': No such file or directory
- initializing webone service
Failed to enable unit: File webone.service: Bad message
Failed to start webone.service: Unit webone.service failed to load properly: Bad message.
See system logs and 'systemctl status webone.service' for details.
● webone.service
     Loaded: error (Reason: Unit webone.service failed to load properly: Bad message.)
     Active: inactive (dead)

Dec 26 13:49:27 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:27 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:29 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:31 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:31 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:41 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:58 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:49:58 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:50:00 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>
Dec 26 13:50:00 raspberrypi systemd[1]: /etc/systemd/system/webone.service:1: Invalid section header '[Unit] Description=WebOne HTTP(S) Proxy Server Documentation=https://github.com/atauenis/webone/>

**Comment by way5** [comment]
Sorry for the delay, I've managed to pull out RPI4 from one of my projects to test this on the real environment.

I've fixed the autoinstall script [webone.arm.sh](https://raw.githubusercontent.com/way5/webone/sandbox/autoinstall/webone.arm.sh).

Webone has been installed and started as service without a problem. 

I hope you can continue with your project now. Let me know how the installation goes. 

~
Merry Christmas and Happy new year!

**Comment by way5** [comment]
--- UPDATE:

In order to perform a clean install I recommend you to run the following commands before you'll continue with autoinstall:

```bash
systemctl disable webone
systemctl daemon-reload
rm -f /etc/systemd/system/webone.service
rm -fr /usr/local/wwebone
rm -fr /etc/webone
```

**Comment by my05** [comment]
Thx heaps way5, it certainly made the trick. Now it builds and runs perfectly.

Merry christmas and happy new year
